/*
	Configuration options used by platform independent code.

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#pragma once

#include <cstdint>

#define EmLocalTalk 0

//#include "HW/wires.h"

#if (CurEmMd == kEmMd_Plus)
#define EmClassicKbrd 1
#define EmADB 0
#define EmRTC 1
#define EmPMU 0
#define EmVIA2 0
#define Use68020 0
#define EmFPU 0
#define EmMMU 0
#define EmASC 0

#define IncludeVidMem 0
#define EmVidCard 0

#define ClockMult 1

#define WantCycByPriOp 1
#define WantCloserCyc 0

#define kRAMa_Size 0x00200000
#define kRAMb_Size 0x00200000

#define RomFileName "vMac.ROM"
constexpr uint32_t kCheckSumRom_Size = 0x00020000;
constexpr uint32_t kRomCheckSum1 = 0x4D1EEEE1;
constexpr uint32_t kRomCheckSum2 = 0x4D1EEAE1;
constexpr uint32_t kRomCheckSum3 = 0x4D1F8172;
constexpr uint32_t kROM_Size = 0x00020000;

/* VIA configuration */
#define VIA1_ORA_FloatVal 0xFF
#define VIA1_ORB_FloatVal 0xFF
#define VIA1_ORA_CanIn 0x80
#define VIA1_ORA_CanOut 0x7F
#define VIA1_ORB_CanIn 0x79
#define VIA1_ORB_CanOut 0x87
#define VIA1_IER_Never0 (1 << 1)
#define VIA1_IER_Never1 ((1 << 3) | (1 << 4))
#define VIA1_CB2modesAllowed 0x01
#define VIA1_CA2modesAllowed 0x01

constexpr uint32_t kExtn_Block_Base = 0x00F40000;
#define kExtn_ln2Spc 5

constexpr uint32_t kROM_Base = 0x00400000;
#define kROM_ln2Spc 20
#endif

#if (CurEmMd == kEmMd_II)

#define EmClassicKbrd 0
#define EmADB 1
#define EmRTC 1
#define EmPMU 0
#define EmVIA2 1
#define Use68020 1
//#define EmFPU 1 //temporarily disable, because it's broken 
#define EmFPU 0
#define EmMMU 0
#define EmASC 1

#define IncludeVidMem 1
constexpr uint32_t kVidMemRAM_Size = 0x00040000;

#define EmVidCard 1
constexpr uint32_t kVidROM_Size = 0x000800;

#define ClockMult 2

#define WantCycByPriOp 0
#define WantCloserCyc 0

#define r_regs "r4"
#define r_pc_p "r5"
#define r_MaxCyclesToGo "r6"
#define r_pc_pHi "r7"

#define kRAMa_Size 0x00400000
#define kRAMb_Size 0x00400000


#define RomFileName "MacII.ROM"
constexpr uint32_t kRomCheckSum1 = 0x97851DB;
constexpr uint32_t kRomCheckSum2 = 0x9779D2C;
constexpr uint32_t kROM_Size = (1 << 18);

/* VIA configuration */
#define VIA1_ORA_FloatVal 0xBF
	/* bit 6 used to check version of hardware */
#define VIA1_ORB_FloatVal 0xFF
#define VIA1_ORA_CanIn 0x80
#define VIA1_ORA_CanOut 0x3F
#define VIA1_ORB_CanIn 0x09
#define VIA1_ORB_CanOut 0xB7
#define VIA1_IER_Never0 0x00
#define VIA1_IER_Never1 0x58
#define VIA1_CB2modesAllowed 0x01
#define VIA1_CA2modesAllowed 0x01

/* VIA 2 configuration */
#define VIA2_ORA_FloatVal 0xFF
#define VIA2_ORB_FloatVal 0xFF
#define VIA2_ORA_CanIn 0x01
#define VIA2_ORA_CanOut 0xC0
#define VIA2_ORB_CanIn 0x00
#define VIA2_ORB_CanOut 0x8C
#define VIA2_IER_Never0 0x00
#define VIA2_IER_Never1 0xED
#define VIA2_CB2modesAllowed 0x01
#define VIA2_CA2modesAllowed 0x01

constexpr uint32_t kCheckSumRom_Size = kROM_Size;

constexpr uint32_t kExtn_Block_Base = 0x50F0C000;
#define kExtn_ln2Spc 5

constexpr uint32_t kROM_Base = 0x00800000;
#define kROM_ln2Spc 20

#endif